### ISSUE TITLE
camel_snake_keys should be included in Formatter::CamelJson

### ISSUE THREAD

**Issue by Aryk** [buermann/introspective_grape#2]
In the event you use the introspective_grape/formatter/camel_json without including the entire library, you will get an error if you include this module since with_camel_keys does not exist on Hash without:

```ruby
require 'camel_snake_keys'
```

Forcing the user to have to require both files:

```ruby
require 'introspective_grape/formatter/camel_json' 
require 'camel_snake_keys'
```

**Comment by buermann** [comment]
Hadn't occurred to me that anybody might try using it to that end. Added the require to 0.2.9. Are you also using those monkey patches for grape-swagger down in lib/introspective_grape/camel_snake.rb, then?

**Comment by Aryk** [comment]
Hi @buermann, thanks for the fast response!

No, I'm not using them because I haven't really incorporated grape-swagger yet. I might eventually, but I'm only incorporating what I'm using right now. The library looks great, but once I start integrating roles, CanCan and other things, I'll have to read through all your code to make sure nothing conflicts and everything connects nicely together. :)

In the meantime, it would be great if you abstracted out:

```ruby
if IntrospectiveGrape.config.camelize_parameters
          child.before_validation do
            # We have to snake case the Rack params then re-assign @params to the
            # request.params, because of the I-think-very-goofy-and-inexplicable
            # way Grape interacts with both independently of each other
            (params.try(:with_snake_keys)||{}).each do |k,v|
              request.delete_param(k.camelize(:lower))
              request.update_param(k, v)
            end
            @params = request.params 
          end
        end
```

Into a mixin/module so that it is not so coupled to your library and then I don't **have to** use the IntrospectiveGrape::API class just to snakecase my parameters. For example, if someone is not doing a restful API but likes your camel -> snake -> camel functionality in your gem, how can they selectively use that for Grape?

I think it's possible others might also want to selectively pick this functionality out of your library, but don't know for sure. Seems like useful functionality! :)

**Comment by buermann** [comment]
There'll definitely be a little noodling necessary to make it agnostic between CanCan and Pundit, maybe not too much.

If you point to the gem's master branch, `require 'introspective_grape/snake_params'` and `extend IntrospectiveGrape::SnakeParams` into your Grape class and call `snake_params_before_validation`  it should underscore the parameter names (I believe that code leaves the camel case keys there just the same). If that works for you I'll bump the version. Seems like writing adequate test coverage for this use case requires a separate test suite, or better kludging on my part to unload the one rails dummy app and loading another...

**Comment by Aryk** [comment]
cool, give me a few days to try it out. Looks good though.

**Comment by Aryk** [comment]
I checked it, it works.

**Comment by buermann** [comment]
Great. It's baked into 0.3.0.

**Comment by Aryk** [comment]
Thanks @buermann .

You know, looking at this again, there might be some issues:

1. You are calling JSON.parse(object.to_json) even if object is already a Hash and has the with_camel_keys method on it, thus unnecessary computations and potential for errors in the marshalling and unmarshalling.
2. MultiJson.dump(object) <-- doesn't that return a String? Why are you calling with_camel_keys on that?
3. The Grape::Formatter::Json already has logic there for to_jsoning objects, why not reuse it. That way if MultiJson gets switched out for something better, it will automatically take advantage of those benefits.

Proposed solution:

```ruby
# Add a formatter to grape that converts all snake case hash keys from ruby to camel case.
require 'camel_snake_keys'
require 'grape/formatter/json'
module IntrospectiveGrape
  module Formatter
    module CamelJson
      def self.call(object, _env)
        if object.respond_to?(:to_json) && !object.respond_to?(:with_camel_keys) &&
          (parsed_object = JSON.parse(object.to_json)).respond_to?(:with_camel_keys)
          object = parsed_object
        end
        object = object.with_camel_keys if object.respond_to?(:with_camel_keys)
        Grape::Formatter::Json.call(object, _env)
      end
    end
  end
end
```

**Comment by buermann** [comment]
Looks good to me, by which I mean considerably better. If you want to submit a PR I don't think it needs any additional test coverage, or I can swap it out myself.

**Comment by Aryk** [comment]
no problem, done :)

**Comment by buermann** [comment]
👍
